### ISSUE TITLE
strange crash on server

### ISSUE THREAD

**Issue by kreezxil** [AlexIIL/AlexIILLib#2]
"strange crash on dedicated forge server"
server crash report: http://pastebin.com/B9VM1B6r
server fml latest: http://pastebin.com/E353FskP
I'm currently using b1419

lexmanos said to contact the coremod authors, you are one of them

**Comment by AlexIIL** [comment]
Sorry for not responding before, but I don't think I cause this crash (I don't edit World server in my coremod). Could you test it without AlexIILLib just to make sure though?

**Comment by kreezxil** [comment]
I think Craftable Animals was to blame, not sure yet, but after taking it
out and resetting my world, things have been very stable. I'd mark this as
closed for now.

**Comment by AlexIIL** [comment]
Thanks for testing.
